- README.md
- docker-compose.yml
- frontend/.dockerignore
- frontend/Dockerfile
closes #21 
Docker configuration for development. Docker-compose starts front end in development mode with hot-reload.
> Docker for development

- frontend/package.json
- frontend/src/App.tsx
- frontend/src/index.tsx
- frontend/src/services/fileService.ts
- frontend/src/store/actions/files.ts
- frontend/src/store/reducers/files.ts
- frontend/src/store/store.ts
- frontend/src/store/types/files.ts
- frontend/yarn.lock
Initial implementation of redux ready for expansion. 
Note: 
- Api call to GitHub from App component moved to a service. 
- Connecting to redux store and the use of actions in component App probably not inline with best practices of today.
- Some very basic conditional logic added to component App when loading files or we encounter an error when loading
- No error handling in services yet
> Initial redux skeleton

- frontend/src/App.tsx
- frontend/src/components/EditView.tsx
- frontend/src/components/ListView.tsx
- frontend/src/store/actions/files.ts
- frontend/src/store/reducers/files.ts
- frontend/src/store/types/files.ts
#29 
* Start using redux hooks
* Fix some typing errors in dispatch
> Use redux hooks & fix dispatch types

- frontend/src/components/EditView.tsx
- frontend/src/components/ListView.tsx
File listing aside code editor.
> file listing aside code editor

- README.md
- documentation/backend.md
- documentation/frontend.md
- documentation/general.md
close #48 
* Documentation folder started with `frontend.md`, `backend.md` & `general.md`
* Some initial documentation added to each file
* Links added to readme
> Start documentation folder and update readme

- README.md
- documentation/general.md
Fixes 3 broken links at README.md
> fixing 3 links in README.md

- README.md
- documentation/backend.md
- documentation/general.md
Fixed 1 typing mistake in general.md.
> fixing friday afternoon typing mistakes

- backend/package.json
- backend/yarn.lock
- docker-compose.server.yml
- docker-compose.yml
- documentation/database.md
- userdata/init_scripts/init.sql
- userdata/userdata.env
closes #45 
closes #60 
usable basic version postgresql
> Set up postgre

- backend/.dockerignore
- backend/.gitignore
- backend/Dockerfile
- backend/package.json
- backend/src/git.ts
- backend/src/schema/repository.ts
- backend/src/schema/schema.ts
- backend/yarn.lock
- docker-compose.server.yml
- docker-compose.yml
- documentation/database.md
- userdata/init_scripts/init.sql
- userdata/userdata.env
closes #39 
- Clones repository to ./repositories/{organization}/{repositoryname}
- GraphQL reponse with repository files and file content
> Git integration

- backend/package.json
- backend/src/git.ts
- backend/src/schema/repository.ts
- backend/src/schema/schema.ts
- backend/yarn.lock
Partly does #19 
- Graphql saveChanges mutation
- Pushes saved file to new branch using given github username and token
> Add file saving and pushing to remote

- .github/workflows/master_push.yml
- .github/workflows/pull_request.yml
- .github/workflows/staging_push.yml
closes #99 
closes #96 
-changed default branch to staging(already done)
-added workflow for staging. Changed existing workflows
> add staging workflow and improve existing workflows

- .github/workflows/master_push.yml
- .github/workflows/staging_push.yml
* Workflow files had wrong indentation and this tries to fix that
> Fix actions again

- frontend/src/App.tsx
- frontend/src/components/MonacoEditor.tsx
- frontend/src/components/auth/CallBack.tsx
When the user logs in via GitHub, the username is displayed on the top of the page in a link. When that same link is clicked, the user can log out.
> Login improvements

- .github/workflows/master_push.yml
- .github/workflows/pull_request.yml
- .github/workflows/staging_push.yml
- backend/package.json
- docker-compose.server.yml
closes #94 
* Change `docker-compose.server.yml` to better match our server's current configurations before I forget
* Simplify github actions workflow files to have less steps and better structure
* Comment if you feel that something could still be improved or perhaps reverted back
> Ci and docker compose changes

- backend/src/git.ts
- backend/src/schema/repository.ts
`cloneRepository` graphql query now pulls changes from origin master to local repository if the repository already exists
closes #90
> Add initial git pull functionality

- backend/services/gitHub.ts
closes #105 
User authentication didn't seem to work with any other github app other than our WEVC Dev (even with duplicate settings). The problem seemed to be that the authentication query didn't work with certain tokens. This hopefully fixes that issue.
> Fix user authentication query

- README.md
- documentation/backend.md
* @tulma95 suggested that fast guide to start development should be found in README
* Improved the definition of done based on our discussions. Feel free to change if I missed something tell me what you think about it.
* Some changes to backend documentation. Feel free to change them aswell if you have any other suggestions.
> Documentation improvements

- backend/jest.config.js
- backend/package.json
- backend/src/schema/repository.ts
- backend/src/schema/schema.ts
- backend/src/services/git.ts
- backend/src/tests/sanitize.test.ts
- backend/src/types/params.ts
- backend/src/utils/sanitize.ts
- backend/src/utils/utils.ts
- backend/yarn.lock
> Issue113 - Backend accepts commit message as an optional parameter

- backend/src/services/git.ts
> Issue115 - Backend creates a new branch if given branch doesn't exist 

- frontend/cypress/integration/editor/editor.spec.js
- frontend/cypress/integration/editor/filelist.spec.js
- frontend/src/App.tsx
- frontend/src/components/EditView.tsx
- frontend/src/components/ListView.tsx
- frontend/src/types.ts
closes #125 
* Frontend felt really buggy with multiple `loading...` notifications when logging in -> fixed this
* Improved some typing in frontend
* Changed layout to better match concept design
* Just small changes to combine `/filelist` & `/editview` but our E2E tests had to be changed a little bit
> Remove frontend duplicate loading and improve layout

- frontend/src/components/MonacoEditor.tsx
- frontend/src/graphql/mutations.ts
> Update frontend to send branch name and commit message to backend

- backend/package.json
- backend/src/index.ts
- backend/src/schema/repository.ts
- backend/src/schema/schema.ts
- backend/src/services/git.ts
- backend/src/tests/git.test.ts
- backend/src/tests/repository.test.ts
- backend/yarn.lock
Closes #149 
- New graphQL query: `getRepoBranches(url: String!)`
- Unit tests for `getBranches(git: SimpleGit)` function
- GraphQL integration tests with `apollo-server-testing`-library for query.
> Issue149 branches query

- frontend/src/components/LoginForm.tsx
- frontend/src/components/MonacoEditor.tsx
Closes #147 
Current branch name is visible in editor view when user has logged in.
The branch automatically updates with the click of save button when user has saved to a new branch.
> Display current branch name in editor view

- backend/Dockerfile
- backend/package.json
- backend/src/index.ts
- backend/src/schema/repository.ts
- backend/src/schema/schema.ts
- backend/src/services/git.ts
- backend/src/tests/git.test.ts
- backend/src/tests/repository.test.ts
- backend/src/tests/userschema.test.ts
- backend/yarn.lock
- frontend/Dockerfile
> apollo server testing initialized

- userdata/init_scripts/init.sql
closes #138 
Updates database to match current plan for database structure. Tech design is available at google drive
> database contains 4 tables with relations

- .github/workflows/master_push.yml
- .github/workflows/pull_request.yml
- .github/workflows/staging_push.yml
- README.md
- backend/.env.dist
- backend/package.json
- backend/src/utils/config.ts
- docker-compose.server.yml
- docker-compose.test.yml
- documentation/backend.md
* Created `docker-compose.test.yml` to start database
* Made `DATABASE_URL` default to testing database when node_env is `test`
* Simplified testing scripts
* Running backend tests with database active:
1. Start `docker-compose.test.yml`
2. Go to backend folder
3. Run `yarn test:setup` to create the tables with migrations
4.. Run `yarn test` to test backend
> Issue172 postgres for testing

- frontend/src/components/MyLoginForm.tsx
- frontend/src/graphql/mutations.ts
> Issue198 fix broken login

- frontend/src/components/MonacoEditor.tsx
> Add branch name to merge conflict error message

- frontend/cypress/integration/editor/editor.spec.js
- frontend/cypress/integration/editor/frontpage.spec.js
- frontend/cypress/integration/editor/login.spec.js
- frontend/cypress/integration/editor/register.spec.js
- frontend/package.json
- frontend/yarn.lock
Closes #185 
Initial e2e tests
> Issue185 e2e tests

- frontend/cypress/integration/editor/editor.spec.js
- frontend/cypress/integration/editor/login.spec.js
- frontend/cypress/integration/editor/register.spec.js
- frontend/src/components/RegisterForm.tsx
After registering, the user logins automatically.
Closes #190
> Login automatically after registering

- frontend/src/components/RegisterForm.tsx
- frontend/src/components/RegisterSchema.tsx
closes #188 
- minimum length of the password is 8(Tatu Kairi's suggestion)
- passwords requirements have precise description, including which special characters can be used.
- Email and username help texts are matching to each others
-confirmation field informs user, if password confirmation does not match with chosen password.
> validations improved

- backend/src/schema/repository.ts
- backend/src/services/git.ts
- backend/src/tests/git.test.ts
- backend/src/tests/utils.test.ts
- backend/src/utils/gitUtils.ts
- backend/src/utils/utils.ts
- backend/yarn.lock
closes #183 
Tried to make the git operations clearer but this was quite a difficult task. There were multiple error cases with our current implementation where commits are made with the local user details and I hope I fixed all of them for now. Also did some quite heavy refactoring because almost every function seemed to do different url string manipulations.
I tried to click through various merge conflict situations and didn't manage to break it but maybe you can.
* Application allowed doing local commits and this caused merge conflicts and errors if remote is updated and page refreshed. Current fix: removed the automatic pull operation from `cloneRepository` when the repo location already exists. Pulling newest changes to repo needs a lot of thinking, e.g. when to do it?
* Merge …
> Issue183- Refactor git operations and fix errors

- backend/package.json
- backend/src/schema/user.ts
- backend/src/tests/userschema.test.ts
- backend/src/utils/validation.ts
- backend/yarn.lock
Closes #187 
- Implemented skeleton for user registration argument validation
- Added basic validation for username, password and email identical to that in frontend
* Validation also returns fitting error messages that could be returned to user if needed
> Issue 187: Backend register validation

- frontend/src/grammars/robot.ts
- frontend/src/grammars/robotConfiguration.ts
- frontend/src/themes/vs-dark-plus-theme.ts
- frontend/src/utils/configuration.ts
- frontend/src/utils/languages.ts
- frontend/src/utils/monacoInitializer.ts
- frontend/src/utils/providers.ts
- frontend/src/utils/wasmLoader.ts
Just added the links to used code for syntax highlighting. Strangely my formatter had not been working originally so now some of the code is formatted on save.
> Issue231 - Add references to used syntax highlighting code

- frontend/cypress/integration/editor/login.spec.js
- frontend/cypress/integration/editor/register.spec.js
- frontend/src/components/Header.tsx
Closes #224 
Restyled global nav
> Issue224 nav buttons

- frontend/src/components/BranchSelector.tsx
- frontend/src/components/FileTreeView.tsx
- frontend/src/components/Header.tsx
- frontend/src/components/Home.tsx
- frontend/src/components/MonacoEditor.tsx
Closes #222 
- Added some margins to various elements in edit view (file tree, title, save button)
- Gave the area above editor static size so that in no longer expands when selecting a file for the first time
- Increased the size of the editor slightly
- Moved the dark mode toggle switch to the right side of the header
- Changed the buttons in home view/main menus to use React Router's hook
- Removed unnecessary theme parameter from BranchSelector 
- Reformatted the files I edited
> Issue222 small adjustments

- frontend/src/components/Home.tsx
closes #243 
Added white color css attribute to register button
> add color css attribute to button
