- frontend/src/components/ListView.tsx
- frontend/src/services/fileService.ts
Linked to #14 
* Changed GitHub API call to use recursion parameter
* Files also save the API url
* ListView displays files as links to URL
* This can be removed/changed as soon as edit view progresses but was left as a demostration for now
> Improve filelist querying

- .github/workflows/master_push.yml
- .github/workflows/node.js.yml
- .github/workflows/pull_request.yml
closes #44 
closes #15 
* GitHub actions changes split into 2 parts
* Master push - full CI/CD
* CI = Install frontend, run normal frontend tests & run cypress tests
* CD = Build and publish frontend image to dockerhub (https://hub.docker.com/repository/docker/ohtuprojekti/wevc) tagged with 
`frontend-latest`. Requires CI to pass
* Pull request - CI only
* CI = Install frontend, run normal frontend tests & run cypress tests
* Actions tab should show ran action `WEVC CI/CD` for `ci-configuration` branch push and `WEVC CI` for pull request to verify operation
> Github actions configuration

- .github/workflows/master_push.yml
#50 had a missing line of code and the master workflow didn't require CI (testing) for CD (docker deployment). This now fixes it.
Note: `ci-configuration` branch as a push target is to be fixed later so only master pushes trigger docker deployment.
> Fix missing CI requirement for CD steps in workflow

- backend/Dockerfile
- backend/package.json
- docker-compose.yml
closes #36 
* `start` script in backend to start built index.js file
* Initial dockerfile for backend
* Docker-compose file starts backend to port 3001, no volumes considered because backend has no hot-reload
> Add initial dockerfile for backend and start backend in docker-compose

- .github/workflows/master_push.yml
- .github/workflows/pull_request.yml
closes #53 
closes #55 
* GitHub actions installs, builds, tests backend (no test script yet) and pushes image to our dockerhub
* Ignores runs when only README.md, LICENSE or documentation folder is modified (I think)
> Add backend operations & documentation ignoring to github actions

- backend/package.json
- docker-compose.server.yml
- docker-compose.yml
- frontend/Dockerfile
* Add hot-reload in backend functionality to development docker-compose
* Add production docker-compose to repo (this should be copied to server as soon as Github actions pushes backend)
* Add `serve` to frontend image, used to serve production version of frontend
* Some other way of serving production frontend should be addressed later
* Express + Apollo?
> Add backend docker hot-reload & docker-compose for server

- .dockerignore
- .github/workflows/master_push.yml
- Dockerfile
- README.md
- backend/package.json
- backend/src/index.ts
- docker-compose.server.yml
closes #69 
* Backend hosts production frontend with express
* Application uses only port 3001 
* Dockerfile added for production
* Github actions changed to push only this single docker image
* Production docker-compose changed to match changes
* Also fixes our server not fetching files in production mode
* Side-effect: GraphQL playground not accessible in production environment (server)
> Express frontend serving & production mode fix

- documentation/frontend.md
- frontend/package.json
- frontend/src/components/auth/GitHubAuthBtn.tsx
- frontend/yarn.lock
closes #116 
- Added [Material-UI](https://material-ui.com/) to frontend.
- Changed the GitHub login button to use Material-UI as a test
- Updated the technologies section of frontend documentation
Material-UI has three different packages
- material-ui/core -> has all the core components
- material-ui/icons -> has a lot of useful [icons](https://material-ui.com/components/material-icons/)
- material-ui/lab -> contains [experimental components](https://material-ui.com/components/about-the-lab/)
- I included this because of the [Tree View](https://material-ui.com/components/tree-view/) component, which looks useful for implementing the file listing in the sidebar
> Add Material-UI

- backend/src/schema/repository.ts
- backend/src/schema/schema.ts
- backend/src/services/git.ts
- backend/src/types/repoState.ts
- frontend/src/components/MonacoEditor.tsx
- frontend/src/graphql/queries.ts
- frontend/src/types.ts
closes #133 
* Started GraphQL query for getting the current state of repository
* Currently only returns active branch name
* Current files could be added to the query later
* Fetch currently active branch name to frontend save modal
* Couldn't make this automatically update with the click of a save. User has to refresh the page after a save if the save is made to new branch (to see the updated branch name in the second save)
* Tried GraphQL `useLazyQuery` but maybe someone could help me with improving this later
> Show current branch name in frontend save dialog

- backend/Dockerfile
- frontend/Dockerfile
`frontend/Dockerfile` & `backend/Dockerfile` had useless `yarn build` because they're only used for development. This was just taking useless time when doing `docker-compose build` and decided to do a very quick fix for this.
> Remove useless build from dev dockerfiles

- backend/src/schema/repository.ts
- backend/src/schema/schema.ts
- backend/src/services/git.ts
- backend/src/tests/git.test.ts
- backend/src/tests/repository.test.ts
- backend/src/types/repoState.ts
- frontend/src/App.tsx
- frontend/src/components/EditView.tsx
- frontend/src/components/MonacoEditor.tsx
- frontend/src/graphql/queries.ts
- frontend/src/types.ts
closes #156 
* `getRepoState` query now returns: current branch name, files in the repo (in current branch) and list of all branch names
* Removed `getRepoBranches` query as a duplicate
* Changed `cloneRepository` query to not return current files anymore
* Changes to frontend to fix current functionality with new queries
* `EditView` component queries repo cloning and repo state
* Frontend is a big mess at the moment, I think `MonacoEditor` component shouldn't do any queries anymore but I left this untouched to address this issue in a different PR
* Added tests for this query
* Some duplicate code and typescript ESLint errors, is this an issue?
> Issue156: Improve query for repository state

- backend/Dockerfile
- documentation/backend.md
- documentation/frontend.md
- frontend/Dockerfile
Realized that development `Dockerfile`'s don't need to install everything with `yarn` because they're meant to be run with our `docker-compose` and the `node_modules` are cloned from developer computer. This will break the dockerfiles so that they can't be run without our `docker-compose` but makes `docker-compose build` a lot faster.
Just remember to run `yarn` in `/backend` and `/frontend` folders before `docker-compose up` (as before)
> Make docker-compose build faster

- backend/src/schema/repository.ts
- backend/src/services/git.ts
- frontend/src/components/MonacoEditor.tsx
closes #146 
Backend returns an error message when a merge conflict is detected.
Now frontend just logs the message when file saving results in a merge conflict.
The error will be handled in frontend in issue #145
> Issue146 merge conflict error

- frontend/src/components/MonacoEditor.tsx
- frontend/src/components/SaveDialog.tsx
closes #145 
If backend return "Merge conflict error" the push to current branch -option is hided and error message is shown to user. The error message persists until user  saves to new branch
> Issue145 merge conflict modal

- .github/workflows/master_push.yml
- .github/workflows/pull_request.yml
- .github/workflows/staging_push.yml
- frontend/cypress/integration/editor/editor.spec.js
- frontend/src/App.tsx
- frontend/src/components/EditView.tsx
- frontend/src/components/FileTreeView.tsx
- frontend/src/components/Header.tsx
- frontend/src/components/ListView.tsx
- frontend/src/components/LoginForm.tsx
- frontend/src/components/MonacoEditor.tsx
- frontend/src/components/Sidebar.tsx
- frontend/src/tests/files.test.ts
- frontend/src/types.ts
- frontend/src/utils/files.ts
Closes #163 
- Modified the layout by adding a sidebar and a header
- Changed the file listing to a tree
- Some refactoring
Originally I wanted to just send a tree structure from the backend but it turns out it's not really possible to query recursive objects  with unknown depth unless you bypass GraphQL type checking completely and just fetch a raw json object, which seems like a bad idea. So because of that the parsing is done in the frontend. The way the tree is built is kinda inefficient but I didn't want to work on it more right now since maybe we end up sending the tree from the backend anyway (with pagination or something).
> Issue163 update file listing

- backend/src/schema/repository.ts
- backend/src/schema/schema.ts
- backend/src/services/git.ts
- backend/src/tests/repository.test.ts
- backend/src/types/params.ts
Closes #169 (I guess?)
- Added backend mutation for switching current branch.
- The mutation takes in the url of the repo and the name of the branch
- Returns back the name of the branch
- This is a quick and temporary solution until DB is ready to store user specific repo state. Mainly did this to define our API so #148 has something to call.
- No tests because the logic will change anyway
> Add branch switching to backend

- backend/src/schema/repository.ts
- backend/src/services/git.ts
closes #176 
The application tried to pull newest changes to `master` which caused a crash after a merge conflict. Here's a quick fix for this problem. I don't know how to test git pulling from remote so now there's no tests for this bug. I will open a refactoring issue after this to start working on making the structure of repository actions a bit more testable and write tests for various situations in there.
> Fix backend error after merge conflict

- backend/src/schema/schema.ts
- backend/src/schema/user.ts
- backend/src/tests/userschema.test.ts
- backend/src/types/user.ts
- frontend/src/graphql/mutations.ts
Closes #189 
Changed the backend mutations register and login to return only token, because currentUser is stored in apollo context and returning the user would have no effect. Changed also related tests and frontend register mutation.
> Issue189 return only token

- frontend/src/App.tsx
- frontend/src/components/AuthenticateDialog.tsx
- frontend/src/components/Header.tsx
- frontend/src/components/MonacoEditor.tsx
- frontend/src/components/RegisterForm.tsx
- frontend/src/components/auth/GitHubAuthBtn.tsx
- frontend/src/styles/themes.ts
Closes #196 
- Added support for dark mode and the ability to change between it and light mode
- Uses the default themes for Monaco Editor. For Material-UI mostly defaults with some colors copied from Material Design [guidelines](https://material.io/design/color/dark-theme.html) for improved legibility
- Selected theme is saved in localStorage to avoid resetting it between reloads
> Issue196 Dark mode

- backend/package.json
- backend/src/schema/schema.ts
- backend/src/schema/user.ts
- backend/src/tests/userschema.test.ts
- frontend/package.json
- frontend/src/components/MonacoEditor.tsx
- frontend/src/graphql/queries.ts
- frontend/src/types.ts
- frontend/yarn.lock
Closes #218 
Backend changes: 
- New graphql query `isGithubConnected: Boolean!` which returns true or false based on if `context.user` has githubToken or not.
- Two tests for the query
Frontend changes:
- Updated @material-ui/icons
- Added `isGIthubConnected` type and query
- Add new `GHConnected` -component which is located and used in `MonacoEditor.tsx`
> Issue218 show GitHub status

- ThirdPartyNotices.txt
Closes #236 
The licenses of the projects we used for syntax highlighting require that the original license is also included in our repo. Now there is `ThirdPartyNotices.txt` file for that.
> Create ThirdPartyNotices.txt and include required licenses
